[package]
name = "Kiosk"
version = "0.0.2"
published-at = "0x1a8ddbe94f664bb8f65535e49bfd78b3fde50035dde30c7428a1abc88fa39265"


[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
kiosk = "0x1a8ddbe94f664bb8f65535e49bfd78b3fde50035dde30c7428a1abc88fa39265"